services:
  postgres:
    image: postgres:latest
    container_name: if-postgres
    restart: always
    volumes:
      - ./docker-compose/postgresql:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
  redis:
    image: redis
    container_name: if-redis
    ports:
      - '6379:6379'
